In [1]:
import torch
import numpy as np
checkpoint = torch.load('/data/rozen/home/e0833634/lama/protllama/pl_model_cache/epoch=23-train_perplexity=1.161-val_perplexity=255.593-ppi_10_26_10k_2048.ckpt')

In [2]:
hyper_parameters = checkpoint["hyper_parameters"]
hyper_parameters

{'hparam': Namespace(accumulate_grad_batches=10, attempts='1', batch_size=1, date='10_26', devices=8, epoch=30, flash_attention=True, hidden_size=1280, input_dataset_path='/home/a03-yzhang/projects/protllama2_data/data/ppi/ppi_8000', intermediate_size=3440, learning_rate=0.0001, max_position_embeddings=2048, num_attention_heads=20, num_hidden_layers=30, num_key_value_heads=20, num_workers=8, output_dataset_path='/home/a03-yzhang/projects/protllama2_output/ppi_8000', save_top_k=3, scheduler='cosine', strategy='ddp', target='ppi', tokenizer_path='/home/a03-yzhang/projects/protllama2_data/data/tokenizers/', train_dataloader_length=22735, vocab_size='10k')}

In [3]:
import sys
sys.path.append('../bin')
from model import pretrainLlama

/opt/rh/rh-python38/root/usr/local/lib64/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")


[2023-11-24 23:43:09,922] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)


2023-11-24 23:43:14.431974: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
from argparse import Namespace
# Namespace is immutable

# Assuming you have the original Namespace object
original_hparam = hyper_parameters['hparam']

# Create a new Namespace object with the updated tokenizer_path
new_hparam = Namespace(
    accumulate_grad_batches=original_hparam.accumulate_grad_batches,
    attempts=original_hparam.attempts,
    batch_size=original_hparam.batch_size,
    date=original_hparam.date,
    devices=original_hparam.devices,
    epoch=original_hparam.epoch,
    flash_attention=original_hparam.flash_attention,
    hidden_size=original_hparam.hidden_size,
    input_dataset_path=original_hparam.input_dataset_path,
    intermediate_size=original_hparam.intermediate_size,
    learning_rate=original_hparam.learning_rate,
    max_position_embeddings=original_hparam.max_position_embeddings,
    num_attention_heads=original_hparam.num_attention_heads,
    num_hidden_layers=original_hparam.num_hidden_layers,
    num_key_value_heads=original_hparam.num_key_value_heads,
    num_workers=original_hparam.num_workers,
    output_dataset_path=original_hparam.output_dataset_path,
    save_top_k=original_hparam.save_top_k,
    scheduler=original_hparam.scheduler,
    strategy=original_hparam.strategy,
    target=original_hparam.target,
    tokenizer_path='/data/rozen/home/e0833634/lama/protllama/batch_script/',  # Update the tokenizer_path here
    train_dataloader_length=original_hparam.train_dataloader_length,
    vocab_size=original_hparam.vocab_size
)

# Update the hyper_parameters with the new Namespace
hyper_parameters['hparam'] = new_hparam

# Print the updated hyper_parameters to confirm the change
print(hyper_parameters)

{'hparam': Namespace(accumulate_grad_batches=10, attempts='1', batch_size=1, date='10_26', devices=8, epoch=30, flash_attention=True, hidden_size=1280, input_dataset_path='/home/a03-yzhang/projects/protllama2_data/data/ppi/ppi_8000', intermediate_size=3440, learning_rate=0.0001, max_position_embeddings=2048, num_attention_heads=20, num_hidden_layers=30, num_key_value_heads=20, num_workers=8, output_dataset_path='/home/a03-yzhang/projects/protllama2_output/ppi_8000', save_top_k=3, scheduler='cosine', strategy='ddp', target='ppi', tokenizer_path='/data/rozen/home/e0833634/lama/protllama/batch_script/', train_dataloader_length=22735, vocab_size='10k')}


In [5]:
model = pretrainLlama(**hyper_parameters)

LlamaConfig {
  "attention_bias": false,
  "bos_token_id": 1,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 1280,
  "initializer_range": 0.02,
  "intermediate_size": 3440,
  "max_position_embeddings": 2048,
  "model_type": "llama",
  "num_attention_heads": 20,
  "num_hidden_layers": 30,
  "num_key_value_heads": 20,
  "pretraining_tp": 1,
  "rms_norm_eps": 1e-06,
  "rope_scaling": null,
  "rope_theta": 10000.0,
  "tie_word_embeddings": false,
  "transformers_version": "4.34.1",
  "use_cache": true,
  "vocab_size": 10000
}



In [6]:
model.configure_model()
model.state_dict()
state_dict = checkpoint['state_dict']
model.load_state_dict(state_dict)

<All keys matched successfully>

In [7]:
from transformers import LlamaTokenizerFast, LlamaForCausalLM
tokenizer = LlamaTokenizerFast('/data/rozen/home/e0833634/lama/protllama/batch_script/protein_10k.model')

You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thouroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565


In [8]:
prompt = "ESQPDPKPDELHKSSKFTGLMENMKVLYDDNHVSAINVKSIDQFLYFDLIYSIKDTKLGNYDNVRVEFKNKDLADKYKDKYVDVFGANYYYQCYFSKKTNDINSHQTDKRKTCMYGGVTEHNGNQLDKYRSITVRVFEDGKNLLSFDVQTNKKKVTAQELDYLTRHYLVKNKKLYEFNNSPYETGYIKFIENENSFWYDMMPAPGDKFDQSKYLMMYNDNKMVDSKDVKIEVYLTTKKK</s>"
inputs = tokenizer(prompt, return_tensors="pt")
inputs

{'input_ids': tensor([[   1,  664,    9, 1564,  835, 2888, 3602, 1329, 2650,  208, 3926,  647,
         3702,  368,  429,  144, 1865, 2583, 3879, 1787, 2407,  857,  139, 1063,
         3998, 1628,  202,  727, 8715, 3004, 3646, 1153, 1444, 4489, 8600, 3056,
           42, 3984, 1421,  327, 2232, 3687,  409, 1917,  945, 3956, 2042, 3646,
         2690,   56, 2171, 1623,  916, 1241, 2968,  214,  860,  667,  559,  561,
         5001, 3735, 7735, 1219, 4099, 3356, 2133, 3481,  191, 1302, 2276, 9569,
         8432,  526, 2610, 5790, 1390,  281, 5220, 6575, 1317, 1808,  120, 2996,
         1607,  860,    2]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [9]:
inputs.input_ids.size()

torch.Size([1, 87])

In [9]:
for key in inputs:
    inputs[key] = inputs[key].to('cuda')

In [10]:
model.model.generation_config.pad_token_id = model.model.generation_config.eos_token_id
model.model.generation_config

GenerationConfig {
  "bos_token_id": 1,
  "eos_token_id": 2,
  "pad_token_id": 2
}

In [11]:
tokenizer.pad_token_id = tokenizer.eos_token_id

In [25]:
model.model.generation_config.max_length = 200
# Parameters for manipulation of the model output logits
model.model.generation_config.repetition_penalty = 1.2
model.model.generation_config.temperature = 0.7 # randomness
#model.model.generation_config.top_p = 0.9
model.model.generation_config.top_k = 950
model.model.generation_config.length_penalty = -0.1
# model.model.generation_config.length_penalty = 1 # < 0 encourage shorter sequences
# Parameters that control the generation strategy used
model.model.generation_config.do_sample = True # use greedy decoding otherwise
# Parameters that define the output variables of `generate`
model.model.generation_config.num_return_sequences = 1
model.model.generation_config.output_scores = True
model.model.generation_config.return_dict_in_generate = True

In [26]:
model.model.generation_config

GenerationConfig {
  "bos_token_id": 1,
  "do_sample": true,
  "eos_token_id": 2,
  "length_penalty": -0.1,
  "max_length": 200,
  "output_scores": true,
  "pad_token_id": 2,
  "repetition_penalty": 1.2,
  "return_dict_in_generate": true,
  "temperature": 0.7,
  "top_k": 950
}

In [27]:
# Define the custom prefix_allowed_tokens function to enforce conditioning on A
model = model.cuda()
with torch.cuda.amp.autocast():
    # Generate text B conditioned on A
    generated_output =model.model.generate(inputs.input_ids,
                                           #prefix_allowed_tokens_fn=custom_prefix_allowed_tokens,
                                           )
generated_output

/data/rozen/home/e0833634/.local/lib/python3.8/site-packages/transformers/generation/configuration_utils.py:418: UserWarning: `num_beams` is set to 1. However, `length_penalty` is set to `-0.1` -- this flag is only used in beam-based generation modes. You should set `num_beams>1` or unset `length_penalty`.
  warnings.warn(
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.


SampleDecoderOnlyOutput(sequences=tensor([[   1,  664,    9, 1564,  835, 2888, 3602, 1329, 2650,  208, 3926,  647,
         3702,  368,  429,  144, 1865, 2583, 3879, 1787, 2407,  857,  139, 1063,
         3998, 1628,  202,  727, 8715, 3004, 3646, 1153, 1444, 4489, 8600, 3056,
           42, 3984, 1421,  327, 2232, 3687,  409, 1917,  945, 3956, 2042, 3646,
         2690,   56, 2171, 1623,  916, 1241, 2968,  214,  860,  667,  559,  561,
         5001, 3735, 7735, 1219, 4099, 3356, 2133, 3481,  191, 1302, 2276, 9569,
         8432,  526, 2610, 5790, 1390,  281, 5220, 6575, 1317, 1808,  120, 2996,
         1607,  860,    2,  600,  567, 5463, 5137, 7488, 4083, 2259, 1635,  515,
         4518, 4797, 9210, 8899, 1689,  451, 1546, 1611,  176, 1545, 4436,   42,
           45, 1155, 6483, 6000,  199, 6638, 1014,  340, 2069, 1519, 4855, 1419,
         8327, 4318, 2154,  124, 2424, 7558,  304, 1715, 2394, 5986, 6542,  604,
           42, 7850,  763, 1247, 4361, 1822, 8144, 6878,    3, 1194, 3791, 

In [15]:
num_tokens_generated = len(generated_output.scores)
num_tokens_generated

113

In [17]:
generated_output.sequences.size()

torch.Size([1, 200])

In [28]:
#works only when you generate one output
def calculate_single_perplexity(output_scores, transition_scores):
    #intializing stuff
    num_tokens_generated = len(output_scores)
    logits_for_every_tok = []
    for i in range(num_tokens_generated):
        logits_for_every_tok.append(output_scores[i]) #only one output, so 0
    specific_logits = transition_scores.tolist() #only one output, so 0

    # initialize a list to hold the indices
    indices = []
    # iterate through each sub-list and the specific logit at the same time
    for i, (sub_list, specific_logit) in enumerate(zip(logits_for_every_tok, specific_logits)):
        # find index of specific logit in the sub-list & use small epsilon for float comparison - round errors
        epsilon = 1e-5
        index = next((idx for idx, val in enumerate(sub_list) if abs(val - specific_logit) < epsilon), None)
        indices.append(index)
    #'indices' now contains the indices of each specific logit in the corresponding sub-list

    log_prob = 0.0
    for i in range(num_tokens_generated):
        #get rid of -inf for numerical stabulity
        logits = [float(k) for k in output_scores[i] if k !=float('-inf')] #btw, you might want to know that len(logits) = top_k
        # Apply the softmax function to convert logits to probabilities
        total_sum = np.exp(logits).sum()
        probability = np.exp(output_scores[i][indices[i]])/total_sum
        #ppl = e^(-(average of log probability)) #https://huggingface.co/docs/transformers/perplexity
        log_prob+=np.log(probability.item())
    ppl = np.exp(-log_prob/len(indices))

    return ppl

In [29]:
def calculate_multiple_perplexity(num_outputs, outputs_scores, transition_scores):
    perplexities = []
    for i in range(num_outputs):
        tran_score = transition_scores[i]
        out_score = []
        for k in outputs_scores:
            out_score.append(k[i].cpu())
        ppl = calculate_single_perplexity(out_score,tran_score)
        perplexities.append(ppl)
    return perplexities

In [28]:
#calculate ppl
transition_scores = model.model.compute_transition_scores(
    generated_output.sequences, generated_output.scores, normalize_logits=False #normalize_logits applies softmax then log
    )
transition_scores_np = np.array(transition_scores.cpu())
transition_scores_np

array([[  3.0050223, -15.368304 ,  23.571428 ,  28.683037 ,  29.107143 ,
         29.66518  ,  21.183037 ,  34.285713 ,  35.46875  ,  27.03125  ,
         28.415178 ,  25.714287 ,  25.736609 ,  26.383928 ,  25.066965 ,
         28.973215 ,  30.401787 ,  21.752234 ,  36.473217 ,  23.660715 ,
         27.120537 ,  55.       ,  30.982143 ,  32.410713 ,  32.34375  ,
         31.160715 ,  25.959822 ,  38.75     ,  27.008928 ,  37.32143  ,
         34.776787 ,  32.901787 ,  32.276787 ,  28.973215 ,  29.6875   ,
         29.151787 ,  33.013393 ,  28.72768  ,  16.875    ,  28.370537 ,
         35.870537 ,  25.558037 ,  23.459822 ,  26.227678 ,  25.825893 ,
         28.255207 ,  34.933037 ,  22.96875  ,  28.88393  ,  32.34375  ,
         26.852678 ,  24.107143 ,  28.57143  ,  30.424109 ,  38.549107 ,
         33.88393  ,  18.883928 ,  27.611609 ,  28.013393 ,  33.616074 ,
         28.147322 ,  26.986609 ,  24.129465 ,  27.700893 ,  19.99628  ,
         30.44643  ,  25.825893 ,  37.79018  ,  22.

In [29]:
transition_scores_np[0]

array([  3.0050223, -15.368304 ,  23.571428 ,  28.683037 ,  29.107143 ,
        29.66518  ,  21.183037 ,  34.285713 ,  35.46875  ,  27.03125  ,
        28.415178 ,  25.714287 ,  25.736609 ,  26.383928 ,  25.066965 ,
        28.973215 ,  30.401787 ,  21.752234 ,  36.473217 ,  23.660715 ,
        27.120537 ,  55.       ,  30.982143 ,  32.410713 ,  32.34375  ,
        31.160715 ,  25.959822 ,  38.75     ,  27.008928 ,  37.32143  ,
        34.776787 ,  32.901787 ,  32.276787 ,  28.973215 ,  29.6875   ,
        29.151787 ,  33.013393 ,  28.72768  ,  16.875    ,  28.370537 ,
        35.870537 ,  25.558037 ,  23.459822 ,  26.227678 ,  25.825893 ,
        28.255207 ,  34.933037 ,  22.96875  ,  28.88393  ,  32.34375  ,
        26.852678 ,  24.107143 ,  28.57143  ,  30.424109 ,  38.549107 ,
        33.88393  ,  18.883928 ,  27.611609 ,  28.013393 ,  33.616074 ,
        28.147322 ,  26.986609 ,  24.129465 ,  27.700893 ,  19.99628  ,
        30.44643  ,  25.825893 ,  37.79018  ,  22.689734 ,  29.7

In [50]:
perplexity = calculate_multiple_perplexity(model.model.generation_config.num_return_sequences, generated_output.scores, transition_scores_np)

[-8.671875, -12.54464340209961, -8.883929252624512, -11.517857551574707, 5.343192100524902, -4.737723350524902, -11.222098350524902, -13.783482551574707, -12.087054252624512, -10.870535850524902, -13.850446701049805, -6.082589626312256, -11.21651840209961, -7.8683037757873535, -9.1015625, -11.506696701049805, -11.852679252624512, -14.017857551574707, -8.883929252624512, -5.842634201049805, -14.02901840209961, -6.010044574737549, -10.892857551574707, 4.561942100524902, -12.611607551574707, 4.43359375, -12.287946701049805, -13.136160850524902, -5.549665451049805, -12.912946701049805, -12.522321701049805, -8.197545051574707, -12.176339149475098, -10.625, 3.275669813156128, -9.26339340209961, -6.428571701049805, 3.0831472873687744, -7.600446701049805, 3.4347097873687744, -9.916295051574707, 2.7762277126312256, -12.600446701049805, -6.456473350524902, -13.046875, -12.756696701049805, -10.625, -11.640625, -12.477679252624512, -9.69308090209961, -9.229910850524902, -11.462054252624512, -13.29

In [43]:
top_k_text = tokenizer.batch_decode(generated_output['sequences'], skip_special_tokens=False, clean_up_tokenization_spaces=True)
top_k_text

['<s> ESQPDPKPDELHKSSKFTGLMENMKVLYDDNHVSAINVKSIDQFLYFDLIYSIKDTKLGNYDNVRVEFKNKDLADKYKDKYVDVFGANYYYQCYFSKKTNDINSHQTDKRKTCMYGGVTEHNGNQLDKYRSITVRVFEDGKNLLSFDVQTNKKKVTAQELDYLTRHYLVKNKKLYEFNNSPYETGYIKFIENENSFWYDMMPAPGDKFDQSKYLMMYNDNKMVDSKDVKIEVYLTTKKK</s> MEGSSSAIARKTWELENNILPVEPTDSASDSIFHYDDASQAKIQQEKPWASDPNYFKRVHISALALLKMVVHARSGGTIEIMGLMQGKTEGDTIIVMDAFALPVEGTETRVNAQSDAYEYMVEYSQTSKLAGRLENVVGWYHSHPGYGCWLSGIDVSTQMLNQQYQEPFLAVVIDPTRTVSAGKVEIGAFRTYPEGHKISDDHVSEYQTIPLNKIEDFGVHCKQYYSLDITYFKSSLDSHLLDLLWNKYWVNTLSSSPLLGNGDYVAGQISDLAEKLEQAESQLANSRYGGIAPAGHQRRKEDEPQLAKITRDSAKITVEQVHGLMSQVIKDIL']

In [44]:
# Extract input and output sequences
input_sequences = []
output_sequences = []

for entry in top_k_text:
    # Split the entry into two parts using </s> as a separator
    parts = entry.split('</s>')

    # Extract the input sequence (without <s>) and the output sequence
    input_seq = parts[0].replace('<s>', '').strip()
    output_seq = parts[1].strip()

    input_sequences.append(input_seq)
    output_sequences.append(output_seq)

In [49]:
input_sequences

['ESQPDPKPDELHKSSKFTGLMENMKVLYDDNHVSAINVKSIDQFLYFDLIYSIKDTKLGNYDNVRVEFKNKDLADKYKDKYVDVFGANYYYQCYFSKKTNDINSHQTDKRKTCMYGGVTEHNGNQLDKYRSITVRVFEDGKNLLSFDVQTNKKKVTAQELDYLTRHYLVKNKKLYEFNNSPYETGYIKFIENENSFWYDMMPAPGDKFDQSKYLMMYNDNKMVDSKDVKIEVYLTTKKK']

In [46]:
output_sequences

['MEGSSSAIARKTWELENNILPVEPTDSASDSIFHYDDASQAKIQQEKPWASDPNYFKRVHISALALLKMVVHARSGGTIEIMGLMQGKTEGDTIIVMDAFALPVEGTETRVNAQSDAYEYMVEYSQTSKLAGRLENVVGWYHSHPGYGCWLSGIDVSTQMLNQQYQEPFLAVVIDPTRTVSAGKVEIGAFRTYPEGHKISDDHVSEYQTIPLNKIEDFGVHCKQYYSLDITYFKSSLDSHLLDLLWNKYWVNTLSSSPLLGNGDYVAGQISDLAEKLEQAESQLANSRYGGIAPAGHQRRKEDEPQLAKITRDSAKITVEQVHGLMSQVIKDIL']

In [48]:
input_sequence_lengths = [len(seq) for seq in input_sequences]
output_sequence_lengths = [len(seq) for seq in output_sequences]
output_sequence_lengths

[334]

In [52]:
import pandas as pd
df = pd.DataFrame({
    'Original Input': input_sequences,
    'Generated Sequence': output_sequences,
    'Perplexity': perplexity,
    'Input_sequence Length': input_sequence_lengths,
    'Output sequence length': output_sequence_lengths
})
df

Original Input  \
0  ESQPDPKPDELHKSSKFTGLMENMKVLYDDNHVSAINVKSIDQFLY...   

                                  Generated Sequence  Perplexity  \
0  MEGSSSAIARKTWELENNILPVEPTDSASDSIFHYDDASQAKIQQE...    1.032258   

   Input_sequence Length  Output sequence length  
0                    239                     334

In [ ]:
model.model.can_generate()

In [76]:
import torch
import numpy as np
logits_for_every_tok = torch.tensor(np.array([[1, 1, float('-inf')], [float('-inf'), 5, 5], [7, 8, 9]]),  dtype=torch.float32)
print(logits_for_every_tok.size())
logits_for_every_tok

torch.Size([3, 3])


tensor([[1., 1., -inf],
        [-inf, 5., 5.],
        [7., 8., 9.]])

In [77]:
specific_logits = torch.tensor((1., 5., 7.),  dtype=torch.float32)
specific_logits = specific_logits.squeeze(0)
print(specific_logits.size())
specific_logits

torch.Size([3])


tensor([1., 5., 7.])

In [78]:
logits_for_every_tok_transposed = logits_for_every_tok.transpose(0, 1)
logits_for_every_tok_transposed

tensor([[1., -inf, 7.],
        [1., 5., 8.],
        [-inf, 5., 9.]])

In [79]:
logits_for_every_tok_transposed.size()

torch.Size([3, 3])

In [80]:
torch.isclose(logits_for_every_tok_transposed, specific_logits, rtol=1e-5)

tensor([[ True, False,  True],
        [ True,  True, False],
        [False,  True, False]])

In [105]:
close_mask = torch.isclose(logits_for_every_tok_transposed, specific_logits, rtol=1e-5)
close_mask

tensor([[ True, False,  True],
        [ True,  True, False],
        [False,  True, False]])

In [119]:
nonzero_indices = torch.nonzero(close_mask, as_tuple=False)
nonzero_indices

tensor([[0, 0],
        [0, 2],
        [1, 0],
        [1, 1],
        [2, 1]])

In [138]:
sorted_indices = nonzero_indices[nonzero_indices[:, 0].argsort()]
sorted_indices

tensor([[0, 0],
        [0, 2],
        [1, 0],
        [1, 1],
        [2, 1]])

In [139]:
unique_indices = torch.unique(sorted_indices[:, 1], sorted=False)
unique_indices

tensor([1, 2, 0])

In [146]:
sorted_indices[sorted_indices[:, 1] == 2]

tensor([[0, 2]])

In [140]:
for i in unique_indices:
    print(sorted_indices[sorted_indices[:, 1] == i][0])

tensor([1, 1])
tensor([0, 2])
tensor([0, 0])


In [137]:
# Find the indices of non-zero elements along axis 0
nonzero_indices = torch.nonzero(close_mask, as_tuple=False)

# Sort the indices based on the first element (axis 0)
sorted_indices = nonzero_indices[nonzero_indices[:, 0].argsort()]

# Get the unique indices along axis 1
unique_indices = torch.unique(sorted_indices[:, 1], sorted=False)

# Extract the corresponding indices along axis 0
filtered_close_indices = torch.stack([sorted_indices[sorted_indices[:, 1] == i][0] for i in unique_indices])
filtered_close_indices

tensor([[1, 1],
        [0, 2],
        [0, 0]])

In [130]:
# Use torch.cumsum to get cumulative sum along rows
cumulative_sum = torch.cumsum(close_mask, dim=0)
cumulative_sum

tensor([[1, 0, 1],
        [2, 1, 1],
        [2, 2, 1]])

In [134]:
first_occurrence_index = torch.argmax(cumulative_sum, dim=0) - 1
first_occurrence_index

tensor([ 0,  1, -1])

In [128]:
filtered_close_indices = []

for i in range(close_mask.size(1)):
    indices = torch.nonzero(close_mask[:, i], as_tuple=False)
    if indices.numel() > 0:
        first_occurrence_index = indices[0, 0].item()
        filtered_close_indices.append([first_occurrence_index, i])

filtered_close_indices = torch.tensor(filtered_close_indices)
filtered_close_indices

tensor([[0, 0],
        [1, 1],
        [0, 2]])

In [58]:
close_indices[0][0].item()

0

In [59]:
close_indices[0][1].item()

0

In [61]:
logits_for_every_tok_transposed[0, 0]

tensor(1.)

In [82]:
mask = (logits_for_every_tok_transposed != -float('inf'))
tensor_exp = torch.exp(logits_for_every_tok_transposed * mask)
tensor_exp

tensor([[2.7183e+00,        nan, 1.0966e+03],
        [2.7183e+00, 1.4841e+02, 2.9810e+03],
        [       nan, 1.4841e+02, 8.1031e+03]])

In [83]:
torch.nan_to_num(tensor_exp, nan=0.0)

tensor([[2.7183e+00, 0.0000e+00, 1.0966e+03],
        [2.7183e+00, 1.4841e+02, 2.9810e+03],
        [0.0000e+00, 1.4841e+02, 8.1031e+03]])

In [63]:
tensor_exp[:, 0]

tensor([2.7183, 7.3891,    nan])

In [84]:
tensor_without_nan = torch.nan_to_num(tensor_exp[:, 0], nan=0.0)
tensor_without_nan

tensor([2.7183, 2.7183, 0.0000])

In [85]:
torch.sum(tensor_without_nan)

tensor(5.4366)

In [87]:
np.exp(logits_for_every_tok_transposed[close_indices[0][0].item(), close_indices[0][1].item()])

tensor(2.7183)

In [43]:
log_prob = 0.0
for i in range(logits_for_every_tok_transposed.size(1)):
    softmax_numerator = np.exp(logits_for_every_tok_transposed[close_indices[i][0].item(), close_indices[i][1].item()])
    softmax_denominator = torch.sum(tensor_exp[:, i])
    probability = softmax_numerator / softmax_denominator
    log_prob += np.log(probability.item())
    print(probability.item())
print(log_prob)

0.09003057299782118
1.8083123363768574
0.012184312411552113
-6.222817989476241


In [34]:
torch.exp(logits_for_every_tok_transposed).sum(dim=0)

tensor([   30.1929,   606.4401, 12180.6758])

In [12]:
mask = (logits_for_every_tok_transposed != -float('inf'))

# Apply the mask and calculate the sum along axis 1
sum_along_axis1 = torch.sum(logits_for_every_tok_transposed * mask, dim=0)
sum_along_axis1

tensor([ 6, 15, 24])

In [18]:
logits_for_every_tok_transposed[close_indices[0].items()]

AttributeError: 'Tensor' object has no attribute 'items'

In [29]:
logits_for_every_tok_transposed[0,2]

tensor(7)

In [24]:
row_indices = close_indices[:, 0]
row_indices

tensor([0, 0, 1])

In [26]:
logits_list = [logit for i, logit in enumerate(logits_for_every_tok_transposed[:, row_indices]) if logits_for_every_tok_transposed[i, row_indices[i]] != float('-inf')]
logits_list

[tensor([1, 1, 4]), tensor([2, 2, 5]), tensor([3, 3, 6])]

In [27]:
logits_for_every_tok_transposed[row_indices, row_indices]

tensor([1, 1, 5])

In [25]:
for i, logit in enumerate(logits_for_every_tok_transposed[:, row_indices]):
    print(i, logit)

0 tensor([1, 1, 4])
1 tensor([2, 2, 5])
2 tensor([3, 3, 6])


In [ ]:
logits_list = [logit for i, logit in enumerate(logits_for_every_tok_transposed[:, row_indices]) if logits_for_every_tok_transposed[i, row_indices[i]] != float('-inf')]
